### ISSUE TITLE
[Fetaure Request] Seperate JWS Parsing in sendAttestationRequest method

### ISSUE THREAD

**Issue by karandpr** [rajivshah3/react-native-google-safetynet#136]
Ohai.
First of all, good work on the plugin ! 

I would like to discuss a feature.
Currently we are using the following workflow

- Generate a nonce on device/server
- Send Attestation Request to Google
- Decode & Verify Response on Device
- Execute Relevant Logic.

One of the use cases while implementing SafetyNet requires JWS verification on server side. The second workflow is below.

- Generate partial nonce on server
- Generate partial nonce on device
- Send Attestation Request to Google
- Send JWS response to server
- Verify JWS response with google on server
- Decode JWS 
- Execute Relevant Logic

A small change to sendAttestationRequest will allow us to execute the second workflow. A developer can then choose to decode JWS on device or send the JWS back to server. All it requires is creating a separate method for JWS decoding. 

```javascript
function sendAttestationRequest(nonce, apiKey) {
    return RNGoogleSafetyNet.sendAttestationRequest(nonce, apiKey).then((result) => {
        return result;
    });
}

function decodeJWS(jwsResponse) {
    return jwtDecode(jwsResponse);
}
```

**Comment by rajivshah3** [comment]
Nice! That sounds good to me. Would you like to do a PR for it?

**Comment by karandpr** [comment]
👍 Sure.I will do that in a day or two.

**Comment by karandpr** [comment]
@rajivshah3  
I did a pull request. 
Originally I wanted to separate the two functions. But I don't really want to break any working logic. 
So instead added an extra function.

**Comment by rajivshah3** [comment]
Thanks! #148
